name: Feature Request
description: Suggest a feature
title: "Feature: <Title>"
labels: [type/enhancement]
body:
- type: dropdown
  attributes:
    label: Which component should be improved?
    options: [Audio, Render, Entity, Gameplay, UI/UX, Other]
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe your suggestion
    description: Give a clear explanation of what you want us to add. Feel free to add pictures or video!
    render: markdown
    placeholder: |
      Please don't give vague suggestions like "Make button look better" or "Add entity that damages the player".
      Think, how does it work. What are the inputs. What is the expected outcome?
      Please discuss your request on [Discord](https://discord.gg/NcHSmgb) before submitting an issue!
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected result
    description: Describe how the end result should look like and work.
    render: markdown
    placeholder: |
      When I do X I want Y to happen.
  validations:
    required: true
