name: Half-Life 2 Bug Report
description: Submit a bug report related to Half-Life 2 maps, entities or other features in P2CE
title: "Half-Life 2 Bug: <Title>"
labels: ["Type: bug", "Priority: Very Low", "Compat: Half-Life 2"]
body:
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear description of what the bug is. Feel free to add pictures or videos (They really help!)
    placeholder: |
      When I do X then Y happens.
  validations:
    required: true
- type: textarea
  attributes:
    label: To Reproduce
    description: Steps to reproduce the behavior
    placeholder: |
      1. Open map ...
      2. Do ...
      3. See error
  validations:
    required: true
- type: input
  attributes:
    label: Operating System
    description: (Optional&#58; Only if OS Specific)
  validations:
    required: false
